repos:
-   repo: local
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        description: Runs hadolint Docker image to lint Dockerfiles
        language: docker_image
        types: ["dockerfile"]
        entry: hadolint/hadolint:v2.8.0 hadolint

-   repo: https://github.com/Yelp/detect-secrets.git
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        description: Check repo for secrets

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-yaml
      name: Validate YAML files
      description: Validate YAML files
    - id: mixed-line-ending
      args: ['--fix=lf']

- repo: https://github.com/atlasense/commit-lint.git
  rev: 0.0.3
  hooks:
    - id: compose-lint
      language: docker_image
      entry: gcr.io/graceful-earth-112011/compose-lint:0.0.1
      files: docker-compose.yaml