
# Example 1:x
services:
  web:
    build: .
    init: true
    container_name: flask-app
    ports:
      - "8000:5000"
    networks:
      - training
  redis:
    image: "redis:6.2.6-bullseye"
    init: true
    container_name: redis
    networks:
      - training

networks:
  training:
    driver: bridge