# Example file

services:
  db:
    image: mysql:8.0.28
    init: true
    container_name: wp-mysql-db
    volumes:
      - db_data:/var/lib/mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp-training

  wordpress:
    image: wordpress:5.9.2
    init: true
    container_name: wp
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    #restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp-training
    depends_on:
      - db

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  wp-training:
    driver: bridge
